/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description Last-known live snapshot (from refresher cache, or built on demand).
         */
        get: operations["get_snapshot_api_live_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Telemetry
         * @description Raw telemetry frames for a single driver in a session.
         */
        get: operations["get_telemetry_api_live_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/circuits/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Circuits */
        get: operations["list_circuits_api_schedule_circuits_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/circuits/{circuit_id}/lap-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Circuit Lap Record
         * @description All-time fastest lap recorded at this circuit across the seasons we
         *     can probe. Pulls Jolpica race results per season and keeps the minimum
         *     `FastestLap.Time` value.
         */
        get: operations["circuit_lap_record_api_schedule_circuits__circuit_id__lap_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Year Schedule */
        get: operations["get_year_schedule_api_schedule__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/{year}/{round_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round */
        get: operations["get_round_api_schedule__year___round_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drivers
         * @description Default: returns the curated current-grid roster (DriverCard objects) for the
         *     requested season, or 2026 if no season is specified.
         *
         *     `?historical=true` returns the legacy list of driver codes from the feature
         *     matrix for back-compat.
         */
        get: operations["list_drivers_api_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Profile */
        get: operations["driver_profile_api_drivers__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standings/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standings */
        get: operations["standings_api_standings__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standings/{season}/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Standings Progression
         * @description Per-round cumulative points for every driver — drives the championship
         *     development line chart on the Standings page.
         */
        get: operations["standings_progression_api_standings__season__progression_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{name}/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Trend */
        get: operations["team_trend_api_teams__name__trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Drivers */
        get: operations["compare_drivers_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/circuits/{circuit_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Circuit History */
        get: operations["circuit_history_api_circuits__circuit_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_predict_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{target}/importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature Importance */
        get: operations["feature_importance_api_models__target__importance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{target}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration */
        get: operations["calibration_api_models__target__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Replays */
        get: operations["list_replays_api_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Meta */
        get: operations["replay_meta_api_replay__season___round_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Snapshot */
        get: operations["replay_snapshot_api_replay__season___round_num__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay Trajectory
         * @description One-shot payload: every driver's session-time-resolution progress curve.
         *
         *     The frontend fetches this once per race, then drives playback locally via
         *     requestAnimationFrame — lerping between samples to get genuinely smooth dot
         *     motion. No per-lap polling required.
         */
        get: operations["replay_trajectory_api_replay__season___round_num__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}/telemetry/{driver_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay Telemetry
         * @description 30 s rolling-window telemetry slice for a single driver, used by the
         *     DriverTelemetry mini-window on the replay page.
         *
         *     Returns 204 when the race's `car_data.ff1pkl` isn't on disk (older
         *     2024/earlier sessions were ingested with `telemetry=False`).
         */
        get: operations["replay_telemetry_api_replay__season___round_num__telemetry__driver_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}/overtakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Overtakes */
        get: operations["replay_overtakes_api_replay__season___round_num__overtakes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{season}/{round_num}/win_probability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Win Probability */
        get: operations["replay_win_probability_api_replay__season___round_num__win_probability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apex/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Apex Next
         * @description Auto-selects the next upcoming race and returns the full prediction bundle.
         */
        get: operations["apex_next_api_apex_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apex/{season}/{round_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Apex Race
         * @description Run the apex prediction for a specific race (any past or upcoming round).
         */
        get: operations["apex_race_api_apex__season___round_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apex/{season}/{round_num}/lap-by-lap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Apex Lap By Lap
         * @description Predicted vs actual finishing position across the race, sampled every
         *     5 laps. Only available for races whose replay data has been ingested.
         */
        get: operations["apex_lap_by_lap_api_apex__season___round_num__lap_by_lap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent-race/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Race
         * @description Most-recently-completed race in `season`. Uses Jolpica (cheap, always
         *     current). Falls back to the schedule + aligned parquet if Jolpica is down.
         */
        get: operations["recent_race_api_recent_race__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApexRaceMeta */
        ApexRaceMeta: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Circuit Id */
            circuit_id?: string | null;
            /** Event Date */
            event_date?: string | null;
        };
        /** ApexResponse */
        ApexResponse: {
            race_meta: components["schemas"]["ApexRaceMeta"];
            top_prediction: components["schemas"]["TopPrediction"];
            /** Podium */
            podium: components["schemas"]["PodiumSlot"][];
            /** Reasoning */
            reasoning: components["schemas"]["PodiumReasoning"][];
            /** Finish P4 P10 */
            finish_p4_p10: components["schemas"]["FinishRow"][];
            reliability: components["schemas"]["ReliabilityScore"];
            /** Generated At */
            generated_at: string;
            /** Quali Source */
            quali_source: string;
        };
        /** CircuitMeta */
        CircuitMeta: {
            /** Circuit Id */
            circuit_id: string;
            /** Name */
            name?: string | null;
            /** Country */
            country?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Lap Length Km */
            lap_length_km?: number | null;
            /** Num Corners */
            num_corners?: number | null;
            /** Drs Zones */
            drs_zones?: number | null;
            /** Downforce Level */
            downforce_level?: string | null;
            /** Overtake Difficulty */
            overtake_difficulty?: number | null;
            /** Typical Air Temp C */
            typical_air_temp_c?: number | null;
            /** Wet Race Rate */
            wet_race_rate?: number | null;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Drivers */
            drivers: string[];
            /** From Season */
            from_season: number;
            /** To Season */
            to_season: number;
            /** Rows */
            rows: components["schemas"]["DriverSeasonRow"][];
        };
        /** ConstructorStandingsRow */
        ConstructorStandingsRow: {
            /** Team Name */
            team_name: string;
            /** Points */
            points: number;
            /** Constructor Position */
            constructor_position: number;
        };
        /** DriverCard */
        DriverCard: {
            /** Driver Code */
            driver_code: string;
            /** Driver Number */
            driver_number?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Team Name */
            team_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
            /** Headshot Url */
            headshot_url?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Country Name */
            country_name?: string | null;
            /**
             * Season Points
             * @default 0
             */
            season_points: number;
            /** Championship Position */
            championship_position?: number | null;
            /** Debut Year */
            debut_year?: number | null;
            /** Experience Years */
            experience_years?: number | null;
        };
        /** DriverPrediction */
        DriverPrediction: {
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name: string;
            /** Quali Position */
            quali_position: number;
            /** Expected Position */
            expected_position: number;
            /** Prob Top10 */
            prob_top10?: number | null;
            /** Prob Podium */
            prob_podium?: number | null;
            /** Prob Win */
            prob_win?: number | null;
            /** Prob Dnf */
            prob_dnf?: number | null;
            /** Prob Fastest Lap */
            prob_fastest_lap?: number | null;
            /** Win Low */
            win_low?: number | null;
            /** Win High */
            win_high?: number | null;
        };
        /** DriverProfile */
        DriverProfile: {
            /** Driver Code */
            driver_code: string;
            /** Current Team */
            current_team?: string | null;
            /**
             * Races
             * @default 0
             */
            races: number;
            /** Avg Finish L5 */
            avg_finish_L5?: number | null;
            /** Avg Finish L10 */
            avg_finish_L10?: number | null;
            /** Dnf Rate L10 */
            dnf_rate_L10?: number | null;
            /** Points L5 */
            points_L5?: number | null;
            /** Season Points */
            season_points?: number | null;
            /** Championship Position */
            championship_position?: number | null;
            /**
             * Season Results
             * @default []
             */
            season_results: components["schemas"]["DriverSeasonResult"][];
            /**
             * Timeline
             * @default []
             */
            timeline: components["schemas"]["DriverSeasonRow"][];
            /** Debut Year */
            debut_year?: number | null;
            /** Experience Years */
            experience_years?: number | null;
            radar?: components["schemas"]["RadarMetrics"] | null;
            /** Aggression Pct */
            aggression_pct?: number | null;
            /** Experience Pct */
            experience_pct?: number | null;
            /**
             * Last 10
             * @default []
             */
            last_10: components["schemas"]["DriverSeasonResult"][];
            /** Headshot Url */
            headshot_url?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Country Name */
            country_name?: string | null;
            /** Driver Number */
            driver_number?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
        };
        /** DriverSeasonResult */
        DriverSeasonResult: {
            /** Round */
            round: number;
            /** Race Name */
            race_name?: string | null;
            /** Circuit Id */
            circuit_id?: string | null;
            /** Grid Position */
            grid_position?: number | null;
            /** Finish Position */
            finish_position?: number | null;
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Is Dnf
             * @default false
             */
            is_dnf: boolean;
        };
        /** DriverSeasonRow */
        DriverSeasonRow: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Driver Code */
            driver_code?: string | null;
            /** Race Name */
            race_name?: string | null;
            /** Circuit Id */
            circuit_id?: string | null;
            /** Team Name */
            team_name?: string | null;
            /** Grid Position */
            grid_position?: number | null;
            /** Finish Position */
            finish_position?: number | null;
            /** Quali Position */
            quali_position?: number | null;
            /** Points */
            points?: number | null;
            /** Is Dnf */
            is_dnf?: boolean | null;
            /** Driver Avg Finish L10 */
            driver_avg_finish_L10?: number | null;
        };
        /** DriverStandingsRow */
        DriverStandingsRow: {
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Points */
            points: number;
            /** Championship Position */
            championship_position: number;
        };
        /** FinishRow */
        FinishRow: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
            /** Est Gap S */
            est_gap_s: number;
            /** Confidence Score */
            confidence_score: number;
            /** At Risk */
            at_risk: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Refresher Running
             * @default false
             */
            refresher_running: boolean;
        };
        /** LapByLapDriverMeta */
        LapByLapDriverMeta: {
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Final Position */
            final_position?: number | null;
        };
        /** LapByLapFrame */
        LapByLapFrame: {
            /** Lap */
            lap: number;
            /** Rows */
            rows: components["schemas"]["LapByLapRow"][];
        };
        /** LapByLapResponse */
        LapByLapResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** N Laps */
            n_laps: number;
            /** Drivers */
            drivers: components["schemas"]["LapByLapDriverMeta"][];
            /** Frames */
            frames: components["schemas"]["LapByLapFrame"][];
        };
        /** LapByLapRow */
        LapByLapRow: {
            /** Driver Code */
            driver_code: string;
            /** Predicted Position */
            predicted_position?: number | null;
            /** Actual Position */
            actual_position?: number | null;
        };
        /** LapRecord */
        LapRecord: {
            /** Circuit Id */
            circuit_id: string;
            /** Driver Code */
            driver_code?: string | null;
            /** Driver Name */
            driver_name?: string | null;
            /** Time */
            time?: string | null;
            /** Season */
            season?: number | null;
            /** Race Name */
            race_name?: string | null;
            /** Average Speed Kph */
            average_speed_kph?: number | null;
        };
        /** LiveDriver */
        LiveDriver: {
            /** Driver Number */
            driver_number?: number | null;
            /**
             * Driver Code
             * @default
             */
            driver_code: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Team Name
             * @default
             */
            team_name: string;
            /** Team Colour */
            team_colour?: string | null;
            /** Headshot Url */
            headshot_url?: string | null;
            /** Position */
            position?: number | null;
            /** Gap To Leader */
            gap_to_leader?: string | null;
            /** Interval */
            interval?: string | null;
            /** Compound */
            compound?: string | null;
            /** Stint Number */
            stint_number?: number | null;
            /** Lap Start */
            lap_start?: number | null;
            /**
             * Pit Count
             * @default 0
             */
            pit_count: number;
        };
        /** LiveSnapshot */
        LiveSnapshot: {
            /** Session Key */
            session_key?: number | null;
            /** Session Name */
            session_name?: string | null;
            /** Session Type */
            session_type?: string | null;
            /** Circuit Short Name */
            circuit_short_name?: string | null;
            /** Country Name */
            country_name?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /**
             * Track Status
             * @default AllClear
             */
            track_status: string | null;
            /**
             * Fetched At
             * @default
             */
            fetched_at: string;
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["LiveDriver"][];
            /**
             * Race Control
             * @default []
             */
            race_control: components["schemas"]["RaceControlMessage"][];
            /**
             * @default {
             *       "rainfall": false
             *     }
             */
            weather: components["schemas"]["WeatherSample"];
        };
        /** ModelManifest */
        ModelManifest: {
            /** Generated At */
            generated_at: string;
            /** Targets */
            targets: components["schemas"]["TargetMetrics"][];
        };
        /** OvertakeEvent */
        OvertakeEvent: {
            /** Lap */
            lap: number;
            /** Time */
            time: number;
            /** Overtaker Code */
            overtaker_code: string;
            /** Overtaker Team */
            overtaker_team?: string | null;
            /** Overtaken Code */
            overtaken_code?: string | null;
            /** Overtaken Team */
            overtaken_team?: string | null;
            /** New Position */
            new_position: number;
        };
        /** OvertakesResponse */
        OvertakesResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Total */
            total: number;
            /** Events */
            events: components["schemas"]["OvertakeEvent"][];
        };
        /** PodiumProbability */
        PodiumProbability: {
            /** Drivers */
            drivers: string[];
            /** Probability */
            probability: number;
        };
        /**
         * PodiumReasoning
         * @description SHAP-templated reasoning blocks for one of the predicted podium
         *     drivers — P1, P2, or P3. Lets the UI surface 'why this whole podium'
         *     instead of just 'why the winner'.
         */
        PodiumReasoning: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
            /**
             * Blocks
             * @default []
             */
            blocks: components["schemas"]["ReasoningBlockOut"][];
        };
        /** PodiumSlot */
        PodiumSlot: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
            /** Prob */
            prob: number;
        };
        /** PredictionRequest */
        PredictionRequest: {
            /**
             * Season
             * @default 2026
             */
            season: number;
            /**
             * Round
             * @default 1
             */
            round: number;
            /** Circuit Id */
            circuit_id: string;
            /**
             * @default {
             *       "air_temp_mean": 25,
             *       "track_temp_mean": 35,
             *       "rainfall": false
             *     }
             */
            weather: components["schemas"]["WeatherForecastInput"];
            /** Quali */
            quali: components["schemas"]["QualiInput"][];
            /** Targets */
            targets?: string[];
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Circuit Id */
            circuit_id: string;
            /** Drivers */
            drivers: components["schemas"]["DriverPrediction"][];
            /**
             * Podium Combinations
             * @default []
             */
            podium_combinations: components["schemas"]["PodiumProbability"][];
        };
        /** ProgressionDriver */
        ProgressionDriver: {
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
            /** Cumulative Points */
            cumulative_points: number[];
        };
        /** ProgressionRound */
        ProgressionRound: {
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
        };
        /** QualiInput */
        QualiInput: {
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name: string;
            /** Quali Position */
            quali_position: number;
            /** Q1 Time Ms */
            q1_time_ms?: number | null;
            /** Q2 Time Ms */
            q2_time_ms?: number | null;
            /** Q3 Time Ms */
            q3_time_ms?: number | null;
            /** Best Quali Time Ms */
            best_quali_time_ms?: number | null;
        };
        /** RaceControlMessage */
        RaceControlMessage: {
            /** Date */
            date?: string | null;
            /** Category */
            category?: string | null;
            /** Flag */
            flag?: string | null;
            /** Message */
            message?: string | null;
            /** Lap Number */
            lap_number?: number | null;
        };
        /** RaceEvent */
        RaceEvent: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Country */
            country: string;
            /** Location */
            location: string;
            /** Circuit Id */
            circuit_id: string;
            /** Event Date */
            event_date?: string | null;
            /** Session5 Date */
            session5_date?: string | null;
            /** Event Format */
            event_format?: string | null;
            /**
             * Has Sprint
             * @default false
             */
            has_sprint: boolean;
            circuit_meta?: components["schemas"]["CircuitMeta"] | null;
            weather_forecast?: components["schemas"]["WeatherForecast"] | null;
        };
        /** RadarMetrics */
        RadarMetrics: {
            /** Qualifying */
            qualifying: number;
            /** Race Pace */
            race_pace: number;
            /** Tyre Mgmt */
            tyre_mgmt: number;
            /** Consistency */
            consistency: number;
            /** Overtaking */
            overtaking: number;
        };
        /** ReasoningBlockOut */
        ReasoningBlockOut: {
            /** Label */
            label: string;
            /** Impact */
            impact: string;
            /** Text */
            text: string;
            /** Feature */
            feature: string;
        };
        /** RecentPodiumRow */
        RecentPodiumRow: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name?: string | null;
        };
        /** RecentRaceResponse */
        RecentRaceResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Circuit Id */
            circuit_id?: string | null;
            /** Date */
            date?: string | null;
            /** Podium */
            podium: components["schemas"]["RecentPodiumRow"][];
        };
        /** ReliabilityScore */
        ReliabilityScore: {
            /** Model Version */
            model_version: string;
            /** Val Metric */
            val_metric?: number | null;
            /** Val Metric Name */
            val_metric_name?: string | null;
            /** Test Metric */
            test_metric?: number | null;
            /** Train Date */
            train_date?: string | null;
            /** Accuracy Pct */
            accuracy_pct: number;
        };
        /** ReplayMeta */
        ReplayMeta: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Circuit Id */
            circuit_id?: string | null;
            /** N Laps */
            n_laps: number;
            /** N Drivers */
            n_drivers: number;
            /**
             * Podium
             * @default []
             */
            podium: components["schemas"]["ReplayPodium"][];
        };
        /** ReplayPodium */
        ReplayPodium: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Team Name */
            team_name: string;
        };
        /** ReplayRaceListEntry */
        ReplayRaceListEntry: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Circuit Id */
            circuit_id?: string | null;
            /** Event Date */
            event_date?: string | null;
            /** N Laps */
            n_laps: number;
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Season */
            season: number;
            /** Events */
            events: components["schemas"]["RaceEvent"][];
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Season
             * @default 2026
             */
            season: number;
            /**
             * Round
             * @default 1
             */
            round: number;
            /** Circuit Id */
            circuit_id: string;
            /**
             * @default {
             *       "air_temp_mean": 25,
             *       "track_temp_mean": 35,
             *       "rainfall": false
             *     }
             */
            weather: components["schemas"]["WeatherForecastInput"];
            /** Quali */
            quali: components["schemas"]["QualiInput"][];
            /** Targets */
            targets?: string[];
            /**
             * N Iterations
             * @default 1000
             */
            n_iterations: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** N Iterations */
            n_iterations: number;
            /** Win Distribution */
            win_distribution: {
                [key: string]: number;
            };
            /** Podium Distribution */
            podium_distribution: {
                [key: string]: number;
            };
            /** Expected Points */
            expected_points: {
                [key: string]: number;
            };
            /** Podium Combinations */
            podium_combinations: components["schemas"]["PodiumProbability"][];
        };
        /** StandingsProgressionResponse */
        StandingsProgressionResponse: {
            /** Season */
            season: number;
            /** Rounds */
            rounds: components["schemas"]["ProgressionRound"][];
            /** Drivers */
            drivers: components["schemas"]["ProgressionDriver"][];
        };
        /** StandingsResponse */
        StandingsResponse: {
            /** Season */
            season: number;
            /** Drivers */
            drivers: components["schemas"]["DriverStandingsRow"][];
            /** Constructors */
            constructors: components["schemas"]["ConstructorStandingsRow"][];
        };
        /** TargetMetrics */
        TargetMetrics: {
            /** Target */
            target: string;
            /** Kind */
            kind: string;
            /** Train Rows */
            train_rows?: number | null;
            /** Val Metric */
            val_metric?: number | null;
            /** Val Metric Name */
            val_metric_name?: string | null;
            /** Test Metric */
            test_metric?: number | null;
            /** Train Date */
            train_date?: string | null;
            /** N Features */
            n_features?: number | null;
        };
        /** TeamTrendRow */
        TeamTrendRow: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Team Name */
            team_name: string;
            /** Points */
            points: number;
        };
        /** TelemetryWindowResponse */
        TelemetryWindowResponse: {
            /** Driver Code */
            driver_code: string;
            /** From T */
            from_t: number;
            /** To T */
            to_t: number;
            /**
             * T
             * @default []
             */
            t: number[];
            /**
             * Speed
             * @default []
             */
            speed: number[];
            /**
             * Throttle
             * @default []
             */
            throttle: number[];
            /**
             * Brake
             * @default []
             */
            brake: boolean[];
            /**
             * Gear
             * @default []
             */
            gear: number[];
            /**
             * Drs
             * @default []
             */
            drs: number[];
        };
        /** TopPrediction */
        TopPrediction: {
            /** Driver Code */
            driver_code: string;
            /** Driver Number */
            driver_number?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Team Name */
            team_name?: string | null;
            /** Team Colour */
            team_colour?: string | null;
            /** Headshot Url */
            headshot_url?: string | null;
            /** Win Prob */
            win_prob: number;
            /** Win Low */
            win_low?: number | null;
            /** Win High */
            win_high?: number | null;
            /** Stochastic Mean */
            stochastic_mean?: number | null;
            /** Description */
            description: string;
        };
        /** TrajectoryCompoundChange */
        TrajectoryCompoundChange: {
            /** Lap */
            lap: number;
            /** Compound */
            compound?: string | null;
            /** Stint */
            stint?: number | null;
        };
        /** TrajectoryDriver */
        TrajectoryDriver: {
            /** Code */
            code: string;
            /** Number */
            number?: number | null;
            /**
             * Team Name
             * @default
             */
            team_name: string;
            /** Team Colour */
            team_colour?: string | null;
            samples: components["schemas"]["TrajectorySamples"];
            /**
             * Compound Changes
             * @default []
             */
            compound_changes: components["schemas"]["TrajectoryCompoundChange"][];
            /**
             * Pit Laps
             * @default []
             */
            pit_laps: number[];
            /**
             * Pit Windows
             * @default []
             */
            pit_windows: components["schemas"]["TrajectoryPitWindow"][];
            /**
             * Lap Times
             * @default []
             */
            lap_times: components["schemas"]["TrajectoryLapTime"][];
            /**
             * Final Lap
             * @default 0
             */
            final_lap: number;
        };
        /** TrajectoryLapTime */
        TrajectoryLapTime: {
            /** Lap */
            lap: number;
            /** T */
            t: number;
            /** Compound */
            compound?: string | null;
        };
        /** TrajectoryPitWindow */
        TrajectoryPitWindow: {
            /** Lap */
            lap: number;
            /** In T */
            in_t: number;
            /** Out T */
            out_t: number;
        };
        /** TrajectoryResponse */
        TrajectoryResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Race Name */
            race_name: string;
            /** Circuit Id */
            circuit_id?: string | null;
            /** N Laps */
            n_laps: number;
            /** Session Duration S */
            session_duration_s: number;
            /**
             * Race Start T
             * @default 0
             */
            race_start_t: number;
            /**
             * Race End T
             * @default 0
             */
            race_end_t: number;
            /** Drivers */
            drivers: components["schemas"]["TrajectoryDriver"][];
            /**
             * Lap Marks
             * @default []
             */
            lap_marks: number[];
            /**
             * Track Status Changes
             * @default []
             */
            track_status_changes: components["schemas"]["TrajectoryStatusChange"][];
            /**
             * Overtakes
             * @default []
             */
            overtakes: components["schemas"]["OvertakeEvent"][];
            /**
             * Sector Marks
             * @default []
             */
            sector_marks: number[];
        };
        /** TrajectorySamples */
        TrajectorySamples: {
            /** T */
            t: number[];
            /** P */
            p: number[];
            /** Pos */
            pos: number[];
            /** Gap */
            gap: (number | null)[];
            /** Int */
            int: (number | null)[];
        };
        /** TrajectoryStatusChange */
        TrajectoryStatusChange: {
            /** T */
            t: number;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /**
             * Api Version
             * @default 1.0.0
             */
            api_version: string;
            /**
             * Python
             * @default
             */
            python: string;
            /**
             * Fastf1
             * @default
             */
            fastf1: string;
        };
        /** WeatherForecast */
        WeatherForecast: {
            /** Air Temp Mean */
            air_temp_mean?: number | null;
            /** Rain Probability Max */
            rain_probability_max?: number | null;
            /** Wind Speed Mean */
            wind_speed_mean?: number | null;
            /**
             * Wet Race Likely
             * @default false
             */
            wet_race_likely: boolean;
        };
        /** WeatherForecastInput */
        WeatherForecastInput: {
            /**
             * Air Temp Mean
             * @default 25
             */
            air_temp_mean: number;
            /**
             * Track Temp Mean
             * @default 35
             */
            track_temp_mean: number;
            /**
             * Rainfall
             * @default false
             */
            rainfall: boolean;
        };
        /** WeatherSample */
        WeatherSample: {
            /** Air Temperature */
            air_temperature?: number | null;
            /** Track Temperature */
            track_temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Wind Speed */
            wind_speed?: number | null;
            /**
             * Rainfall
             * @default false
             */
            rainfall: boolean;
        };
        /** WinProbabilityFrame */
        WinProbabilityFrame: {
            /** Lap */
            lap: number;
            /** Rows */
            rows: components["schemas"]["WinProbabilityRow"][];
        };
        /** WinProbabilityResponse */
        WinProbabilityResponse: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** N Laps */
            n_laps: number;
            /** Drivers */
            drivers: string[];
            /** Frames */
            frames: components["schemas"]["WinProbabilityFrame"][];
        };
        /** WinProbabilityRow */
        WinProbabilityRow: {
            /** Driver Code */
            driver_code: string;
            /** Prob */
            prob: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    get_snapshot_api_live_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSnapshot"];
                };
            };
        };
    };
    get_telemetry_api_live_telemetry_get: {
        parameters: {
            query: {
                driver_number: number;
                /** @description OpenF1 session_key */
                session_key: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_circuits_api_schedule_circuits_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CircuitMeta"][];
                };
            };
        };
    };
    circuit_lap_record_api_schedule_circuits__circuit_id__lap_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_year_schedule_api_schedule__year__get: {
        parameters: {
            query?: {
                include_weather?: boolean;
            };
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_api_schedule__year___round_num__get: {
        parameters: {
            query?: {
                include_weather?: boolean;
            };
            header?: never;
            path: {
                year: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drivers_api_drivers_get: {
        parameters: {
            query?: {
                /** @description Return DriverCards for this season */
                season?: number | null;
                /** @description Return legacy list of code strings */
                historical?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverCard"][] | string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_profile_api_drivers__code__get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_api_standings__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_progression_api_standings__season__progression_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    team_trend_api_teams__name__trend_get: {
        parameters: {
            query?: {
                from_season?: number | null;
                to_season?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamTrendRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_drivers_api_compare_get: {
        parameters: {
            query: {
                /** @description Comma-separated driver codes (e.g. VER,LEC) */
                drivers: string;
                from_season?: number;
                to_season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    circuit_history_api_circuits__circuit_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_predict_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelManifest"];
                };
            };
        };
    };
    feature_importance_api_models__target__importance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_api_models__target__calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_replays_api_replay_get: {
        parameters: {
            query?: {
                /** @description Filter by season */
                season?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRaceListEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_meta_api_replay__season___round_num__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_snapshot_api_replay__season___round_num__snapshot_get: {
        parameters: {
            query?: {
                lap?: number;
            };
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_trajectory_api_replay__season___round_num__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_telemetry_api_replay__season___round_num__telemetry__driver_code__get: {
        parameters: {
            query: {
                /** @description Session time (seconds) — window start */
                from_t: number;
                /** @description Session time (seconds) — window end */
                to_t: number;
            };
            header?: never;
            path: {
                season: number;
                round_num: number;
                driver_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryWindowResponse"];
                };
            };
            /** @description Telemetry not cached for this race */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_overtakes_api_replay__season___round_num__overtakes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OvertakesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_win_probability_api_replay__season___round_num__win_probability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WinProbabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apex_next_api_apex_next_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApexResponse"];
                };
            };
        };
    };
    apex_race_api_apex__season___round_num__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apex_lap_by_lap_api_apex__season___round_num__lap_by_lap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapByLapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_race_api_recent_race__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentRaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
